In [2]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6],[7,8,9]])

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
flat = arr.flatten()

In [4]:
flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
flat[0]

np.int64(1)

In [6]:
flat[1]

np.int64(2)

In [8]:
flat[3:6]

array([4, 5, 6])

In [9]:
flat[0]

np.int64(1)

In [11]:
flat[:5] #same as [0:5]
flat[3:] #same as [3:9]

array([4, 5, 6, 7, 8, 9])

In [12]:
flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
b = flat[3:7].copy() #.copy will create a copy and dont change original data 

In [14]:
b

array([4, 5, 6, 7])

In [15]:
b[0]= 444

In [16]:
b

array([444,   5,   6,   7])

In [17]:
flat

array([  1,   2,   3, 444,   5,   6,   7,   8,   9])

In [21]:
arr1 = np.array([[1,2,3] , [4,5,6], [7,8,9]])

In [22]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr1.shape

(3, 3)

In [29]:
arr2 = np.array([1.1, 2.2, 3.3], dtype = 'int')

In [30]:
arr2.dtype

dtype('int64')

In [38]:
arr3 = np.arange(1, 7)

In [39]:
arr3[arr3 % 2 == 0]

array([2, 4, 6])

In [40]:
arr4 = np.arange(1, 10)

In [41]:
arr4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
matrix = arr4.reshape(3, 3)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
arr5 = np.arange(1, 100)
arr5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [45]:
result = arr5[arr5 > 50]
result

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [1]:
arr

NameError: name 'arr' is not defined

In [2]:
arr5

NameError: name 'arr5' is not defined

In [6]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr[0]

array([1, 2, 3])

In [4]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.sum(arr, axis =0)

array([12, 15, 18])