In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6])

In [3]:
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
arr.dtype

dtype('int64')

In [5]:
arr.astype("float64")

array([1., 2., 3., 4., 5., 6.])

In [6]:
arr.nbytes

48

In [7]:
result = arr ** 2
print(result)

[ 1  4  9 16 25 36]


In [8]:
result + 10

array([11, 14, 19, 26, 35, 46])